### ISSUE TITLE
Support partial `:locals`

### ISSUE THREAD

**Issue by bugeats** [olivernn/poirot#1]
It appears that the handler ignores local variables passed to a partial.

**Comment by bartiaco** [comment]
True that.

**Comment by olivernn** [comment]
Sorry, totally missed this one when it was raised, will take a look at it over the weekend.

**Comment by charlotte-miller** [comment]
Related Pull Request https://github.com/olivernn/poirot/pull/2

**Comment by olivernn** [comment]
I have just pushed a new release which supports locals.  Locals are available as variables within your templates and view classes.

```
<%= render :partial => "some partial", :locals => { :foo => "foo", :bar => "bar" } %>
```

Inside your template you can now just access foo and bar

```
<h1>{{foo}}</h1>
```

Let me know if you find any issues with this.
