### ISSUE TITLE
Use erb or haml in stache templates

### ISSUE THREAD

**Issue by oli-g** [olivernn/poirot#10]
It would be wonderful if stache could handle template files like `_posts.html.haml.mustache` or `_posts.html.erb.mustache`.
Is is possibile? I can help if you provide me with the right directions!

Thank you for this wonderful gem!

**Comment by olivernn** [comment]
Would those templates be ran through haml or erb first then be handled by mustache?  Sounds interesting, what would the use case for this be though?

I think someone had a fork of this project to make it work with hamstache which I think is mustache with a more haml like syntax, I'm not sure how far they got with it though.  Take a look in the forks of this project.

**Comment by oli-g** [comment]
Ok, I will check the forks. Thank you for your feedback!

**Comment by joevandyk** [comment]
I think they would be processed by haml, then by mustache. hamstache doesn't seem to work with newer versions of Rails.
