### ISSUE TITLE
View class can't handle nested attributes

### ISSUE THREAD

**Issue by Darcbar** [olivernn/poirot#19]
How can I add a view class method for something like {{ user.username }}?

**Comment by olivernn** [comment]
From what I understand you can't access nested attributes in mustache using dot syntax.  There are a couple of ways you can get around this though.

If the user object has been serialised then you should be able to access it like so:

```
{{#user}}
  {{username}}
{{/user}}
```

You could also define a method on you view object that returns the username, perhaps something like this:

```
def username
  @user.username
end
```

And then in your template you could do this:

```
{{username}}
```

If there are a lot of attributes within user that you want to access you could delegate these methods to the user, with ruby you could do something like this in your view class:

```
class MyView
  extend Forwardable

  def_delegator :@user, :username, :username
end
```

I think in rails they make delegation a little nicer so you could do this:

```
class MyView
  delegate :username, to: :user
end
```

Take a look at the following links if that isn't clear [Rails delegate](http://api.rubyonrails.org/classes/Module.html#method-i-delegate) and Ruby's [forwardable](http://www.ruby-doc.org/stdlib-1.9.3/libdoc/forwardable/rdoc/Forwardable.html)

Hope that helps!

**Comment by Darcbar** [comment]
Thats great, Thanks olivernn.
