### ISSUE TITLE
poirot.js not loaded in Rails 3.1.1 ruby 1.8.7

### ISSUE THREAD

**Issue by grigio** [olivernn/poirot#8]
I see <script id="post-list-template" filled but no poirot.js is loaded.
I tried adding poirot to application.js but it didn't fixed it

**Comment by olivernn** [comment]
What version of poirot is this in?

Also are there any errors listed in the browser console?  Is jQuery being loaded?  Is the poirot object available in the browser console?

**Comment by grigio** [comment]
I don't know, now  on my Linux machine it works. Cool!

I just confirm that I had to append it to the application.js to have the the js part.

```
//= require poirot
```

**Comment by olivernn** [comment]
Yeah, the poirot JavaScript needs to be added to the application.js manifest file for it to be available in the browser.  I think this is in the Readme but I'll try and make it more clear.
